version: 0.0.{build}
image: 
- Visual Studio 2017
- ubuntu
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: dotnet build -c Release
- ps: dotnet pack -c Release --output ../Package /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION
artifacts:
- path: Package/TogglHeatmap.*.nupkg