version: 0.0.{build}
image: 
- Visual Studio 2017 Preview
- ubuntu
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- cmd: powershell iwr https://github.com/dotnet/cli/raw/v2.1.300/scripts/obtain/dotnet-install.ps1 -outfile dotnet-install.ps1
- cmd: powershell .\dotnet-install.ps1 -Version 2.1.300 -InstallDir $env:ProgramFiles/dotnet
- cmd: powershell .\build.environment.ps1
- cmd: psake appveyor-install
- sh: printf "Commands with sh Prefix run on Linux image only"
- sh: sudo apt-get update
- sh: sudo apt-get install dotnet-sdk-2.1 -y
build_script:
- ps: Write-Host "APPVEYOR=$env:APPVEYOR"
- ps: dotnet build -c Release
- ps: dotnet pack -c Release --output Package /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION
artifacts:
- path: Package/TogglHeatmap.*.nupkg
deploy:
- provider: GitHub
  release: $(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: hH6A9i7v+sf5mZy9FLQVG7n4UpLWkUhpshIsia7sGi1ONr+iMKroqjkJk0Hsi3nK
  artifact: /.*\.nupkg/
  prerelease: true
  on:
    branch: /master/
    APPVEYOR_REPO_TAG: true
    CI_WINDOWS: true
- provider: NuGet
  api_key:
    secure: 4XLKYHbHXYJuc9SCTYZt5VzxE/XDBpjWSttRIK3ZGux5TwIgAnhMBamo16fjVmzS
  on:
    branch: /master/
    APPVEYOR_REPO_TAG: true
    CI_WINDOWS: true
